artifacts_root: artifacts

  # to change the data source, edit the data_ingestion section below
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/SohamBorkar/Text-Summarizer/raw/refs/heads/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

#check for availability of all required files
data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]